- name: LARAVEL | Passport Keys
  shell: php artisan passport:keys
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
    creates: "{{ ansistrano_release_path.stdout }}/storage/oauth-private.key"
- name: LARAVEL | Yarn 
  command: yarn
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"
- name: LARAVEL | build assets 
  command: npm run prod
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"